apiVersion: v1
kind: Pod
metadata:
  name: busybox-cm-env1
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep","2000"]
    env:
    - name: DBUSER
      valueFrom:
        configMapKeyRef:
          name: mycm
          key: DBUSER
