apiVersion: v1
kind: Pod
metadata:
  name: busybox-env
spec:
  containers:
  - name: busybox-env
    image: busybox
    command: ['sh','-c', 'sleep 1000']
    env:
    - name: DBUSER
      value: Smith
    - name: DBPWD
      value: zxtuwxy2nr3
