apiVersion: v1
kind: Pod
metadata:
  name: busybox-secret-env2
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep","2000"]
    envFrom:
    - secretRef:
        name: mysecret
