apiVersion: v1
kind: Pod
metadata:
  name: busybox-cm-vol
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep","2000"]
    volumeMounts:
    - name: myvol
      mountPath: /tmp
  volumes:
  - name: myvol
    configMap:
      name: mycm


