apiVersion: v1
kind: Pod
metadata:
  name: busybox-secret-env1
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep","2000"]
    env:
    - name: DBUSER
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: DBUSER
